#!/bin/bash
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

usage() {
        cat <<EOF
usage:
  ./failchecker [testcase]

  [testcase]: test case to run until fail.
EOF
}

precheck() {
	for classname in `echo $1 | tr -s "," " "`; do
		javasrc=$classname".java"
		find . -name $javasrc | grep $javasrc
		if [ "$?" -eq 1 ];
		then
			echo Not found $classname
			exit 1
		fi
	done
}

if [ $# -ne 1 ];
then
        usage
        exit 1
fi

testcase=$1
i=0

precheck $testcase

while :
do
        i=$(expr $i + 1)
        echo "start to run $1 (try: $i)"

        # TODO: check command failure
	mvn test -Dtest=$testcase > failchecker.log
        if [ "$?" -eq 1 ];
        then
		echo Failed! For more detail, Please check failchecker.log
		exit 1
        fi
done

